# SPDX-FileCopyrightText: 2023 - 2024 Slavi Pantaleev
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Perform APISIX installation tasks
  when: apisix_enabled | bool
  tags:
    - setup-all
    - setup-apisix
    - install-all
    - install-apisix
  block:
    - name: Validate APISIX configuration
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"
    - name: Install APISIX
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"

- name: Perform APISIX uninstallation tasks
  when: not apisix_enabled | bool
  tags:
    - setup-all
    - setup-apisix
  block:
    - name: Uninstall APISIX
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
